import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import os from "node:os";
import type { MediaStorage } from "./MediaStorage";

/**
 * Deterministic local filesystem storage for development and tests. Requires no
 * cloud credentials.
 *
 * Security:
 *  - Keys are validated against a strict allow-list pattern and resolved
 *    against the base dir; any attempt to escape the base (path traversal) is
 *    rejected. Keys are opaque/random and server-generated, so this is defense
 *    in depth, not the primary control.
 */
export class LocalMediaStorage implements MediaStorage {
  private readonly baseDir: string;

  constructor(baseDir?: string) {
    this.baseDir =
      baseDir && baseDir.length > 0
        ? baseDir
        : path.join(os.tmpdir(), `luvora-media-${process.pid}-${crypto.randomUUID()}`);
  }

  /** Resolve a key to an absolute path, refusing anything outside baseDir. */
  private resolve(key: string): string {
    // Keys are generated by this app as "media/<uuid>/<name>" segments.
    if (!/^[a-zA-Z0-9/_-]+$/.test(key) || key.includes("..")) {
      throw new Error("Invalid storage key");
    }
    const full = path.resolve(this.baseDir, key);
    const baseResolved = path.resolve(this.baseDir);
    if (full !== baseResolved && !full.startsWith(baseResolved + path.sep)) {
      throw new Error("Storage key escapes base directory");
    }
    return full;
  }

  async put(key: string, data: Buffer, _contentType: string): Promise<void> {
    const full = this.resolve(key);
    await fs.mkdir(path.dirname(full), { recursive: true });
    await fs.writeFile(full, data);
  }

  async get(key: string): Promise<Buffer> {
    return fs.readFile(this.resolve(key));
  }

  async delete(key: string): Promise<void> {
    try {
      await fs.unlink(this.resolve(key));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    }
  }

  async exists(key: string): Promise<boolean> {
    try {
      await fs.access(this.resolve(key));
      return true;
    } catch {
      return false;
    }
  }

  async getAccessUrl(key: string, _ttlSeconds: number): Promise<string> {
    // The local provider has no externally reachable URL; the application
    // serves bytes through its own authenticated endpoint. Return an internal
    // marker purely to satisfy the interface.
    return `local://${key}`;
  }
}
