/** Standard API response envelope. Errors never leak internals (see §52). */

export interface ApiError {
  code: string;
  message: string;
  details?: unknown;
}

export interface ApiSuccess<T> {
  success: true;
  data: T;
}

export interface ApiFailure {
  success: false;
  error: ApiError;
}

export type ApiResponse<T> = ApiSuccess<T> | ApiFailure;

/** Well-known error codes shared with clients. */
export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  AGE_RESTRICTED: "AGE_RESTRICTED",
  SESSION_NOT_AUTHORIZED: "SESSION_NOT_AUTHORIZED",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  // Discovery & matching (Increment 2).
  USER_NOT_FOUND: "USER_NOT_FOUND",
  CANNOT_INTERACT_WITH_SELF: "CANNOT_INTERACT_WITH_SELF",
  INTERACTION_NOT_ALLOWED: "INTERACTION_NOT_ALLOWED",
  MATCH_NOT_FOUND: "MATCH_NOT_FOUND",
  MATCH_NOT_AUTHORIZED: "MATCH_NOT_AUTHORIZED",
  // Chat (Increment 3).
  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  CHAT_NOT_AUTHORIZED: "CHAT_NOT_AUTHORIZED",
  MATCH_NOT_ACTIVE: "MATCH_NOT_ACTIVE",
  MESSAGE_TOO_LONG: "MESSAGE_TOO_LONG",
  MESSAGE_EMPTY: "MESSAGE_EMPTY",
  INVALID_CURSOR: "INVALID_CURSOR",
  INVALID_WEBSOCKET_MESSAGE: "INVALID_WEBSOCKET_MESSAGE",
  // Fantasy engine (Increment 4).
  SCENARIO_NOT_FOUND: "SCENARIO_NOT_FOUND",
  SCENARIO_NOT_PUBLISHED: "SCENARIO_NOT_PUBLISHED",
  SCENARIO_NOT_AVAILABLE: "SCENARIO_NOT_AVAILABLE",
  SESSION_NOT_READY: "SESSION_NOT_READY",
  SESSION_NOT_PLAYING: "SESSION_NOT_PLAYING",
  GAME_NOT_AUTHORIZED: "GAME_NOT_AUTHORIZED",
  INVALID_CHOICE: "INVALID_CHOICE",
  CHOICE_NOT_AVAILABLE: "CHOICE_NOT_AVAILABLE",
  CONSENT_REQUIRED: "CONSENT_REQUIRED",
  GAME_STATE_CONFLICT: "GAME_STATE_CONFLICT",
  GAME_ALREADY_COMPLETED: "GAME_ALREADY_COMPLETED",
  // Media (Increment 5).
  MEDIA_NOT_FOUND: "MEDIA_NOT_FOUND",
  MEDIA_NOT_AUTHORIZED: "MEDIA_NOT_AUTHORIZED",
  MEDIA_INVALID_STATE: "MEDIA_INVALID_STATE",
  MEDIA_TYPE_NOT_ALLOWED: "MEDIA_TYPE_NOT_ALLOWED",
  MEDIA_TOO_LARGE: "MEDIA_TOO_LARGE",
  MEDIA_INVALID_CONTENT: "MEDIA_INVALID_CONTENT",
  MEDIA_MIME_MISMATCH: "MEDIA_MIME_MISMATCH",
  MEDIA_NOT_READY: "MEDIA_NOT_READY",
  MEDIA_REJECTED: "MEDIA_REJECTED",
  TOO_MANY_ATTACHMENTS: "TOO_MANY_ATTACHMENTS",
  ATTACHMENTS_TOO_LARGE: "ATTACHMENTS_TOO_LARGE",
  // Admin / safety (Increment 6).
  FORBIDDEN_ROLE: "FORBIDDEN_ROLE",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",
  REPORT_NOT_FOUND: "REPORT_NOT_FOUND",
  REPORT_INVALID_TRANSITION: "REPORT_INVALID_TRANSITION",
  DUPLICATE_REPORT: "DUPLICATE_REPORT",
  INVALID_REPORT_TARGET: "INVALID_REPORT_TARGET",
  CANNOT_TARGET_SELF: "CANNOT_TARGET_SELF",
  INVALID_MODERATION_TRANSITION: "INVALID_MODERATION_TRANSITION",
  USER_NOT_FOUND_ADMIN: "USER_NOT_FOUND",
  CANNOT_SUSPEND_SELF: "CANNOT_SUSPEND_SELF",
  LAST_ADMIN: "LAST_ADMIN",
  INVALID_ROLE: "INVALID_ROLE",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
